[package]
name = "jawk"
version = "0.1.11"
edition = "2021"
license = "MIT"
description = "JSON AWK."
homepage = "https://jawk.ykaplan.me/"
repository = "https://github.com/yift/jawk"
documentation = "https://jawk.ykaplan.me/"
readme = "README.md"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
lazy_static = "1.4"
thiserror = "1.0"
indexmap = "2.2"
regex = "1.10"
chrono = "0.4"
cached = "0.49"
base64 = "0.22"
bigdecimal = "0.4"
termimad = { version = "0.29", optional = true }
clap-markdown = { version = "0.1", optional = true }
mdbook = { version = "0.4", optional = true }

[features]
default = ["termimad-help"]
termimad-help = ["termimad"]
create-docs = ["clap-markdown", "mdbook"]
