[package]
name = "jawk"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
lazy_static = "1.4"
thiserror = "1.0"
indexmap = "2.2"
regex = "1.10"
chrono = "0.4"
cached = "0.48"
termimad = { version = "0.29", optional = true }
clap-markdown = { version = "0.1", optional = true }
mdbook = { version = "0.4", optional = true }

[features]
default = ["termimad-help"]
termimad-help = ["termimad"]
create-docs = ["clap-markdown", "mdbook"]