[package]
name = "jawk"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
lazy_static = "1.4"
thiserror = "1.0"
indexmap = "2.1"
regex = "1.10"
chrono = "0.4"
cached = "0.47"