name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run check
      run: cargo check --verbose
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Format
      run: cargo fmt --all --check --verbose
    - name: Run Clippy
      run: cargo clippy --verbose -- -D warnings

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Tarpaulin
      run: cargo install cargo-tarpaulin
    - name: Create Report
      run: cargo tarpaulin --out Html --fail-under 50
    - uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./tarpaulin-report.html
        
  build:
    needs:
      - verify
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ''
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: '.exe'
    steps:
      - uses: actions/checkout@master
      - name: build
        run: cargo build --release --verbose
      - uses: actions/upload-artifact@v3
        with:
          name: jawk-${{ matrix.target }}
          path: ./target/release/jawk${{ matrix.suffix }}
  build-musl:
    needs:
      - verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build
        uses:  stevenleadbeater/rust-musl-builder@master
        with:
          args: /bin/bash -c "cargo build --release --target=x86_64-unknown-linux-musl"
      - uses: actions/upload-artifact@v3
        with:
          name: jawk-x86_64-unknown-linux-musl
          path: ./target/release/jawk
