name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run check
      run: cargo check
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Run Format
      run: cargo fmt --all --check
    - name: Run Clippy
      run: cargo clippy -- -D warnings

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Tarpaulin
      run: cargo install cargo-tarpaulin
    - name: Create Report
      run: cargo tarpaulin --out Html --fail-under 50
    - uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./tarpaulin-report.html
        retention-days: 1
